### ISSUE TITLE
Proper return codes

### ISSUE THREAD

**Issue by dpalanivel** [PowerShell/Microsoft.PowerShell.Archive#58]
Using compress-archive cmdlet in powershell, doesn't seem to return a proper error code when the compression level is invalid.
Could you please check?

Sample code below. **Please make a note of invalid compression level**.

```

$somethingworked=$false

compress-archive -path "c:\source" -destinationpath "C:\source\test.zip" -Force -compressionlevel test

$lastExitCode

if ( $LASTEXITCODE -ne 0) {
    throw "Last command was not successful"
}else {
    $somethingworked=$true
    Write-Host "Value for the boolean variable: $somethingworked"
}

if( $somethingworked) {
    Write-Host "Hey.. Now I'm able to check the previous step's status and it was successful"
}

```

**Comment by nlsdg** [comment]
This works correctly for me with PS 7.0.3 while running your commands inside a scriptfile. It throws a "Last command was not succesful"
The compressionlevel is guarded by a validateset (but that has been in the code for 5 years.), so that hasn't changed.

Maybe the behaviour of the $Lastexitcode has changed. But the documentation I found while searching seems to point to it being the returncode of the last windows application, and shouldn't be used for CmdLets. You might want to change to Try{} Catch{} or the use of the orter error variable $?...

**Comment by ayousuf23** [comment]
`$LASTEXITCODE` is set by executables and batch scripts, I believe. PowerShell cmdlets would not evaluate `$LASTEXITCODE -ne 0` as true even if an error occurred.
